# Writes proxy/vk_spirv.h: the SPIR-V of `selftest vulkan`'s shaders (a VS, a FS, a CS), compiled once with glslang.
#   python proxy/vk_spirv.py <glslang.exe>          (glslang 16.6.0, https://github.com/KhronosGroup/glslang/releases)
# Each shader multiplies by one marker constant; the probe overwrites that OpConstant word with a seed per run, so every
# run's modules are new to the driver (like selftest's seeded HLSL). The unrolled chains make a cold compile cost
# milliseconds, so a cache hit stands out.
import os, random, struct, subprocess, sys, tempfile

MARKERS = {'vs': 0.123456, 'fs': 0.234567, 'cs': 0.345678}


def chain(n, rnd):
    ops = ['v = sin(v.yzwx * {a} + v * {b});', 'v = fract(v * {a}) + cos(v.wxyz * {b});', 'v = v * v.zwxy * {a} + exp2(-abs(v) * {b});']
    return '\n'.join('    ' + ops[i % 3].format(a='%.5f' % rnd.uniform(0.5, 2), b='%.5f' % rnd.uniform(0.5, 2)) for i in range(n))


def sources():
    rnd = random.Random(7)
    return {
        'vs': '#version 450\nlayout(location = 0) in vec4 pos;\nlayout(location = 0) out vec4 col;\nvoid main() {\n'
              '    vec4 v = pos * %f;\n%s\n    gl_Position = v;\n    col = v;\n}\n' % (MARKERS['vs'], chain(48, rnd)),
        'fs': '#version 450\nlayout(location = 0) in vec4 col;\nlayout(location = 0) out vec4 o;\n'
              'layout(set = 0, binding = 0) uniform U { vec4 u; };\nlayout(constant_id = 0) const float K = 1.0;\nvoid main() {\n'
              '    vec4 v = col + u * %f;\n%s\n    o = v * K;\n}\n' % (MARKERS['fs'], chain(160, rnd)),
        'cs': '#version 450\nlayout(local_size_x = 64) in;\nlayout(set = 0, binding = 0) buffer B { vec4 d[]; };\nvoid main() {\n'
              '    vec4 v = d[gl_LocalInvocationIndex] * %f;\n%s\n    d[gl_LocalInvocationIndex] = v;\n}\n' % (MARKERS['cs'], chain(160, rnd)),
    }


def main():
    glslang = sys.argv[1]
    out = ['// Generated by proxy/vk_spirv.py (glslang 16.6.0, --target-env vulkan1.0). Do not edit.', '#pragma once',
           '#include <cstdint>', '']
    with tempfile.TemporaryDirectory() as tmp:
        for stage, src in sources().items():
            s, o = os.path.join(tmp, 'x.' + {'vs': 'vert', 'fs': 'frag', 'cs': 'comp'}[stage]), os.path.join(tmp, stage + '.spv')
            open(s, 'w').write(src)
            subprocess.run([glslang, '-V', '--target-env', 'vulkan1.0', s, '-o', o], check=True, stdout=subprocess.DEVNULL)
            words = struct.unpack('<%dI' % (os.path.getsize(o) // 4), open(o, 'rb').read())
            marker = struct.unpack('<I', struct.pack('<f', MARKERS[stage]))[0]
            assert words.count(marker) == 1, stage
            out.append('static const uint32_t kSpv_%s_marker = 0x%08x;  // %f' % (stage, marker, MARKERS[stage]))
            out.append('static const uint32_t kSpv_%s[] = {' % stage)
            out += ['    ' + ', '.join('0x%08x' % w for w in words[i:i + 10]) + ',' for i in range(0, len(words), 10)]
            out += ['};', '']
    open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'vk_spirv.h'), 'w', newline='\n').write('\n'.join(out))


if __name__ == '__main__':
    main()
